export const SITE_URL = 'https://www.thecurriculumcompass.com'
export const SITE_NAME = 'The Curriculum Compass'
export const SITE_TAGLINE = 'Find Your Perfect Homeschool Curriculum'
export const SITE_LAST_UPDATED = '2026-08-02'
export const SITE_CONTACT_EMAIL = 'hello@thecurriculumcompass.com'
